核心文件更新按钮

diff --git a/root/usr/libexec/navidrome-call b/root/usr/libexec/navidrome-call
--- a/root/usr/libexec/navidrome-call
+++ b/root/usr/libexec/navidrome-call
@@ -14,7 +14,7 @@ get_latest_version() {
 # 获取本地文件的版本号
 get_local_version() {
     if [ -x "$Program_path" ]; then
-        local_version=$(/tmp/navidrome/path/navidrome -v | awk '{print $1}')
+        local_version=$(${Program_path} -v | awk '{print $1}')
         echo "$local_version"
     else
         echo "0.0.0"  # 如果本地文件不存在
@@ -26,9 +26,10 @@ compare_versions() {
     local_version=$(get_local_version)
 
     if [ "$local_version" == "$latest_version" ]; then
-        echo "`date "+%Y-%m-%d %H:%M:%S"`【info】本地文件已经是最新版本 ($local_version)，无需更新" >> $log_path
+        echo "`date "+%Y-%m-%d %H:%M:%S"` 【info】本地文件已经是最新版本 ($local_version)，无需更新" >> $log_path
+        exit 2
     else
-        echo "`date "+%Y-%m-%d %H:%M:%S"`【info】本地文件不是最新版本 ($local_version -> $latest_version)" >> $log_path
+        echo "`date "+%Y-%m-%d %H:%M:%S"` 【info】本地文件不是最新版本 ($local_version -> $latest_version)" >> $log_path
         # download
         download
         /etc/init.d/navidrome stop
@@ -41,21 +42,21 @@ compare_versions() {
 download() {
     download_url="https://github.com/navidrome/navidrome/releases/download/v${latest_version}/navidrome_${latest_version}_linux_amd64.tar.gz"
 
-    echo "`date "+%Y-%m-%d %H:%M:%S"`【info】正在下载 Navidrome $latest_version 到 $download_path..." >> $log_path
+    echo "`date "+%Y-%m-%d %H:%M:%S"` 【info】正在下载 Navidrome $latest_version 到 $download_path..." >> $log_path
     mkdir -p "$download_path"
     curl -L "$download_url" -o "$download_path/navidrome_$latest_version_linux_amd64.tar.gz"
-    [ $? -ne 0 ] && echo "`date "+%Y-%m-%d %H:%M:%S"`【error】二进制文件下载错误，退出!" >> $log_path && exit
-    echo "`date "+%Y-%m-%d %H:%M:%S"`【info】下载完成!" >> $log_path
+    [ $? -ne 0 ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【error】二进制文件下载错误，退出!" >> $log_path && exit
+    echo "`date "+%Y-%m-%d %H:%M:%S"` 【info】下载完成!" >> $log_path
 }
 
 # 安装从临时目录下载的Navidrome
 update() {
-    echo "`date "+%Y-%m-%d %H:%M:%S"`【info】解压到 $Program_path..." >> $log_path
+    echo "`date "+%Y-%m-%d %H:%M:%S"` 【info】解压到 $Program_path..." >> $log_path
     mkdir -p "$extraction_path"
     mkdir -p "$(dirname "$Program_path")"
     tar -xz -C "$extraction_path" -f "$download_path/navidrome_$latest_version_linux_amd64.tar.gz"
     mv "$extraction_path/navidrome" "$Program_path"
-    echo "`date "+%Y-%m-%d %H:%M:%S"`【info】Navidrome $latest_version 更新完成!" >> $log_path
+    echo "`date "+%Y-%m-%d %H:%M:%S"` 【info】Navidrome $latest_version 更新完成!" >> $log_path
     # 清理：删除临时下载和解压目录
     rm -rf "$download_path" "$extraction_path"
 }
@@ -67,7 +68,7 @@ if [ "$1" == "download" ]; then
 	update
 elif [ "$1" == "update" ]; then
 	latest_version=$(get_latest_version)
-	compare_versions
+	compare_versions &
 elif [ "$1" == "clear_log" ]; then
 	> $log_path
 fi
